# Generated by Django 4.1 on 2022-08-24 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ratings', models.PositiveIntegerField(default=2)),
                ('city', models.CharField(default='', max_length=100)),
                ('images', models.ImageField(blank=True, upload_to='HotelImages')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(max_length=100)),
                ('beds', models.PositiveIntegerField(default=2)),
                ('room_description', models.TextField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('price', models.IntegerField(default=0)),
                ('room_images', models.ImageField(blank=True, upload_to='RoomImages')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.hoteladmin')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255, unique=True)),
                ('food_price', models.IntegerField()),
                ('food_type', models.CharField(max_length=255)),
                ('food_image', models.ImageField(blank=True, upload_to='FoodImages')),
                ('hotel_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.hoteladmin')),
            ],
        ),
    ]
