# Generated by Django 4.1 on 2022-08-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_room_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price',
            new_name='room_price',
        ),
    ]
