# Generated by Django 4.0.3 on 2022-08-25 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booked_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('payment_amount', models.IntegerField()),
                ('payment_type', models.CharField(max_length=255)),
                ('bookings_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.bookings')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=255)),
                ('cus_cnic', models.IntegerField(unique=True)),
                ('cus_username', models.CharField(max_length=255, unique=True)),
                ('cus_email', models.EmailField(max_length=255, unique=True)),
                ('cus_password', models.CharField(max_length=50)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.room')),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.customer'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.room'),
        ),
    ]
